# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63f63128539d3fda8c7c00553724e7afcb324e9c5c592c280ddb36140962d079dc54fc0fecda38df7a2f13f51c81a244774ceac514df5dd1fa555ee5c40b6502

test:
  secret_key_base: ff29556f368c4137ce3760e8bacb5d841e1fc0b309491feae9860a26577f2033a80c396fbb7bbbbb648e4ccdb4c3e11739da6c9701aa86bf6a3adf62c1735912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
